import React from 'react';

// This component is the main dashboard shown after a user logs in.
// It receives props to navigate, display user info, and handle logout.
function Dashboard({ navigate, user, onLogout }) {

  // An array of objects to define the different collaboration zones.
  // This makes it easy to add or modify zones in the future.
  const zones = [
    { name: 'Teaching', icon: 'fa-chalkboard-teacher', desc: 'Interactive classrooms with advanced teaching tools', page: 'teaching' },
    { name: 'Gaming', icon: 'fa-gamepad', desc: 'Casual gaming environment with voice chat', page: 'gaming' },
    { name: 'Events', icon: 'fa-calendar-alt', desc: 'Host large events with presentation tools', page: 'events' },
    { name: 'Chill', icon: 'fa-music', desc: 'Relaxed environment for socializing', page: 'chill' },
    { name: 'Workspace', icon: 'fa-building', desc: '3D virtual office with custom avatars', page: 'workspace', featured: true },
  ];

  return (
    <>
      {/* Dashboard-specific navigation bar */}
      <nav className="navbar dashboard-nav">
        <div className="nav-container">
          <div className="nav-logo">
            <h2>Hackifyy</h2>
          </div>
          <div className="nav-user">
            <span>Welcome, <strong>{user?.name || 'User'}</strong></span>
            <button className="logout-btn" onClick={onLogout}>
              <i className="fas fa-sign-out-alt"></i> Logout
            </button>
          </div>
        </div>
      </nav>

      <div className="dashboard-container">
        <div className="dashboard-header">
          <h1>Choose Your Collaboration Zone</h1>
          <p>Select the perfect environment for your needs</p>
        </div>

        {/* The grid of zone cards is generated by mapping over the 'zones' array */}
        <div className="zones-grid">
          {zones.map(zone => (
            <div 
              key={zone.name} 
              className={`zone-card ${zone.page}-zone ${zone.featured ? 'featured' : ''}`} 
              onClick={() => navigate(zone.page)}
            >
              <div className="zone-icon">
                <i className={`fas ${zone.icon}`}></i>
              </div>
              <div className="zone-content">
                <h3>{zone.name} Zone</h3>
                <p>{zone.desc}</p>
              </div>
              <div className="zone-arrow">
                <i className="fas fa-arrow-right"></i>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

export default Dashboard;
